services:
  dev-peerly-postgres-db:
    image: postgres:18
    container_name: dev-peerly-postgres-db
    environment:
      POSTGRES_USER: peerly-postgres-user
      POSTGRES_PASSWORD: peerly-postgres-password
      POSTGRES_DB: peerly-postgres-db-name
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql
    networks:
      - dev-peerly-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U peerly-postgres-user -d peerly-postgres-db-name'"]
      interval: 10s
      timeout: 5s
      retries: 5

  dev-peerly-postgres-migrations:
    image: migrate/migrate:4
    container_name: dev-peerly-postgres-migrations
    networks:
      - dev-peerly-network
    restart: no
    depends_on:
      dev-peerly-postgres-db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgres://peerly-postgres-user:peerly-postgres-password@dev-peerly-postgres-db:5432/peerly-postgres-db-name?sslmode=disable", "up"]

  dev-peerly-app:
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: prod-peerly-app
    env_file:
      - .env
    depends_on:
      prod-peerly-postgres-db:
        condition: service_healthy
      prod-peerly-postgres-migrations:
        condition: service_completed_successfully
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - prod-peerly-network
    restart: unless-stopped

networks:
  dev-peerly-network:
    driver: bridge